/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Cliente;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClienteApiServiceApi
 */
@Disabled
public class ClienteApiServiceApiTest {

    private final ClienteApiServiceApi api = new ClienteApiServiceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void consultarClientePorDniTest() throws ApiException {
        String dni = null;
        Cliente response = api.consultarClientePorDni(dni);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void consultarClientePorIdTest() throws ApiException {
        String id = null;
        Cliente response = api.consultarClientePorId(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createClienteTest() throws ApiException {
        Cliente cliente = null;
        Cliente response = api.createCliente(cliente);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateClienteTest() throws ApiException {
        Cliente cliente = null;
        Cliente response = api.updateCliente(cliente);
        // TODO: test validations
    }

}
