/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.time.LocalDate;
import org.openapitools.client.model.Pedido;
import org.openapitools.client.model.PedidoDetalle;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PedidoApiServiceApi
 */
@Disabled
public class PedidoApiServiceApiTest {

    private final PedidoApiServiceApi api = new PedidoApiServiceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void aadirDetalleTest() throws ApiException {
        String id = null;
        PedidoDetalle pedidoDetalle = null;
        Pedido response = api.aadirDetalle(id, pedidoDetalle);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void buscarPedidoPorIdTest() throws ApiException {
        String id = null;
        Pedido response = api.buscarPedidoPorId(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void buscarPedidosPorClienteTest() throws ApiException {
        String dni = null;
        List<Pedido> response = api.buscarPedidosPorCliente(dni);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void buscarPorFechasTest() throws ApiException {
        LocalDate desde = null;
        LocalDate hasta = null;
        List<Pedido> response = api.buscarPorFechas(desde, hasta);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void crearPedidoTest() throws ApiException {
        Pedido pedido = null;
        String response = api.crearPedido(pedido);
        // TODO: test validations
    }

}
