/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Articulo
 */
public class ArticuloTest {
    private final Articulo model = new Articulo();

    /**
     * Model tests for Articulo
     */
    @Test
    public void testArticulo() {
        // TODO: test Articulo
    }

    /**
     * Test the property 'codigo'
     */
    @Test
    public void codigoTest() {
        // TODO: test codigo
    }

    /**
     * Test the property 'descripcion'
     */
    @Test
    public void descripcionTest() {
        // TODO: test descripcion
    }

    /**
     * Test the property 'precio'
     */
    @Test
    public void precioTest() {
        // TODO: test precio
    }

}
