/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Articulo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PedidoDetalle
 */
public class PedidoDetalleTest {
    private final PedidoDetalle model = new PedidoDetalle();

    /**
     * Model tests for PedidoDetalle
     */
    @Test
    public void testPedidoDetalle() {
        // TODO: test PedidoDetalle
    }

    /**
     * Test the property 'articulo'
     */
    @Test
    public void articuloTest() {
        // TODO: test articulo
    }

    /**
     * Test the property 'cantidad'
     */
    @Test
    public void cantidadTest() {
        // TODO: test cantidad
    }

}
