/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Cliente;
import org.openapitools.client.model.PedidoDetalle;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Pedido
 */
public class PedidoTest {
    private final Pedido model = new Pedido();

    /**
     * Model tests for Pedido
     */
    @Test
    public void testPedido() {
        // TODO: test Pedido
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'cliente'
     */
    @Test
    public void clienteTest() {
        // TODO: test cliente
    }

    /**
     * Test the property 'fecha'
     */
    @Test
    public void fechaTest() {
        // TODO: test fecha
    }

    /**
     * Test the property 'numero'
     */
    @Test
    public void numeroTest() {
        // TODO: test numero
    }

    /**
     * Test the property 'detalles'
     */
    @Test
    public void detallesTest() {
        // TODO: test detalles
    }

}
