/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Articulo;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PedidoDetalle
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-06T17:49:12.031616+01:00[Europe/Madrid]", comments = "Generator version: 7.11.0")
public class PedidoDetalle {
  public static final String SERIALIZED_NAME_ARTICULO = "articulo";
  @SerializedName(SERIALIZED_NAME_ARTICULO)
  @javax.annotation.Nonnull
  private Articulo articulo;

  public static final String SERIALIZED_NAME_CANTIDAD = "cantidad";
  @SerializedName(SERIALIZED_NAME_CANTIDAD)
  @javax.annotation.Nullable
  private Integer cantidad;

  public PedidoDetalle() {
  }

  public PedidoDetalle articulo(@javax.annotation.Nonnull Articulo articulo) {
    this.articulo = articulo;
    return this;
  }

  /**
   * Get articulo
   * @return articulo
   */
  @javax.annotation.Nonnull
  public Articulo getArticulo() {
    return articulo;
  }

  public void setArticulo(@javax.annotation.Nonnull Articulo articulo) {
    this.articulo = articulo;
  }


  public PedidoDetalle cantidad(@javax.annotation.Nullable Integer cantidad) {
    this.cantidad = cantidad;
    return this;
  }

  /**
   * Get cantidad
   * minimum: 1
   * @return cantidad
   */
  @javax.annotation.Nullable
  public Integer getCantidad() {
    return cantidad;
  }

  public void setCantidad(@javax.annotation.Nullable Integer cantidad) {
    this.cantidad = cantidad;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PedidoDetalle pedidoDetalle = (PedidoDetalle) o;
    return Objects.equals(this.articulo, pedidoDetalle.articulo) &&
        Objects.equals(this.cantidad, pedidoDetalle.cantidad);
  }

  @Override
  public int hashCode() {
    return Objects.hash(articulo, cantidad);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PedidoDetalle {\n");
    sb.append("    articulo: ").append(toIndentedString(articulo)).append("\n");
    sb.append("    cantidad: ").append(toIndentedString(cantidad)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("articulo");
    openapiFields.add("cantidad");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("articulo");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PedidoDetalle
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PedidoDetalle.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PedidoDetalle is not found in the empty JSON string", PedidoDetalle.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PedidoDetalle.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PedidoDetalle` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PedidoDetalle.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `articulo`
      Articulo.validateJsonElement(jsonObj.get("articulo"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PedidoDetalle.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PedidoDetalle' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PedidoDetalle> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PedidoDetalle.class));

       return (TypeAdapter<T>) new TypeAdapter<PedidoDetalle>() {
           @Override
           public void write(JsonWriter out, PedidoDetalle value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PedidoDetalle read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PedidoDetalle given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PedidoDetalle
   * @throws IOException if the JSON string is invalid with respect to PedidoDetalle
   */
  public static PedidoDetalle fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PedidoDetalle.class);
  }

  /**
   * Convert an instance of PedidoDetalle to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

