/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import ceu.dam.ad.api.actor.client.ApiException;
import ceu.dam.ad.api.actor.client.api.ActorApiServiceApi;
import ceu.dam.ad.api.actor.client.model.Actor;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ActorApiServiceApi
 */
@Disabled
public class ActorApiServiceApiTest {

    private final ActorApiServiceApi api = new ActorApiServiceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void actualizarCocheTest() throws ApiException {
        Actor actor = null;
        Actor response = api.actualizarCoche(actor);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void borrarTest() throws ApiException {
        Integer id = null;
        api.borrar(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void buscarPorFechaTest() throws ApiException {
        LocalDate fecha1 = null;
        LocalDate fecha2 = null;
        List<Actor> response = api.buscarPorFecha(fecha1, fecha2);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void buscarPorNombreApellidoTest() throws ApiException {
        String filtro1 = null;
        List<Actor> response = api.buscarPorNombreApellido(filtro1);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void consultarTest() throws ApiException {
        Integer id = null;
        Actor response = api.consultar(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void crearTest() throws ApiException {
        Actor actor = null;
        Actor response = api.crear(actor);
        // TODO: test validations
    }

}
